# Generated by Django 4.2 on 2023-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT',
            fields=[
                ('CPF', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('PHONE', models.CharField(max_length=22)),
                ('REGISTERED', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=6)),
                ('QUANTITY', models.IntegerField(default=0)),
                ('REGISTERED', models.DateTimeField()),
            ],
        ),
    ]
